config/routes.rb
SampleApp::Application.routes.draw do
resources :users

  root to: 'estatic_pages#home'

  get '/singup', to: 'users#new'

  get '/help', to: 'estatic_pages#help'
  get '/about', to: 'estatic_pages#about'
  get '/contact', to: 'estatic_pages#contact'

  

end

app/models/user.rb
class User < ActiveRecord::Base

	before_save { |user| user.email = email.downcase }

	validates :name, presence:true, length: {maximum:50}

	VALID_EMAIL_PATTERN = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence:true, format: { with: VALID_EMAIL_PATTERN}, uniqueness: { case_sensitive: false}
	has_secure_password
	validates :password, presence: true, length: {minimum:6}		
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/estatic_pages_controller.rb
class EstaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find(params[:id])
	end

  	def new
  		@user = User.new
  	end

  	def create
  		@user = User.new(user_params)
  		if @user.save
  			flash[:success] = "Wellcome to the Sample App!"
  			redirect_to @user
  		else
  			render 'new'
  		end
  	end

  	private

  	def user_params
  		params.require(:user).permit(:name, :email, :password, :password_confirmation)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/estatic_pages_helper.rb
module EstaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	# Returns the gravatar (http://gravatar.com/) for the given user.
	def gravatar_for (user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "http://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/estatic_pages/about.html.erb
<% provide(:title,'About Us') %>
<h1>About Us</h1>
<p>
The <a href="http://google.com/">Ruby on Rails Tutorial</a> is a project to make a book and screencasts    to teach web development with <a href="http://google.com/">Ruby on Rails</a>. This is the sample application for the tutorial OPTIMIZED.
</p>

app/views/estatic_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
	Contact Ruby on Rails Tutorial about the sample app at the
	<a href="">Contact Page</a>
</p>

app/views/estatic_pages/help.html.erb
<% provide(:title,'Help') %>
<h1>Help</h1>
<p>
Get help on the Ruby on Rails Tutorial at the <a href="http://google.com">Google page</a>.To get help on    this sample app, see the <a href="http://google.com">Rails Tutorial book OPTIMIZED </a>.
</p>	

app/views/estatic_pages/home.html.erb
<!--<% provide(:title,'Home') %>-->
<div>
	<h1>Welcome to the Sample App</h1>
	<h2>
		This is the home page for the <a href="">Ruby on Rails Tutorial</a> sample application
	</h2>
	<%= link_to "Sing up now!", singup_path, class: "btn btn-large btn-primary" %>
</div>
<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/', class: "imgRails" %>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href="">Rails Tutorial</a> by Michael Beltran
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li><a href="http://news.railstutorial.org/">Rails</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "sample app", '#', id: "logo" %>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Home", root_path %></li>
					<li><%= link_to "Help", help_path %></li>
					<li><%= link_to "Sing in", '#' %></li>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Ruby on Rails Tutorial Sample App | <%= yield(:title) %></title>
	<%= stylesheet_link_tag  "application", :media => "all" %>
	<%= javascript_include_tag  "application" %>
	<%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<!--<header class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<%= link_to "sample app", '#', id: "logo"%>
				<nav>
					<ul class="nav pull-right">
						<li><%= link_to "Home", '#' %></li>
						<li><%= link_to "Help", '#' %></li>
						<li><%= link_to "About us", '#' %></li>
						<li><%= link_to "Sing in", '#' %></li>
					</ul>
				</nav>
			</div>
		</div>
	</header>-->
	<div class="container">

		<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %>">
				<%= value %>
			</div>
		<% end %>

		<%= yield %>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(@user.errors.count, "error") %>
		</div>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
				<li>* <%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sing up</h1>
<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>

			<%= render 'shared/error_messages' %>

			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.label :password %>
			<%= f.text_field :password %>

			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.text_field :password_confirmation %>

			<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.name) %>
<div class="row">
	<aside class="span4">
		<section>
			<h1>
				<%= gravatar_for @user %>
				<%= @user.name %>
			</h1>
		</section>
	</aside>
</div>